from typing import Generic, TypeVar

T = TypeVar("T")
S = TypeVar("S", default=str)

class Box(Generic[T]):
    def get(self) -> T: ...

class Sub(Box[S], Generic[S]): ...
class Recursive(Box["Recursive[S]"], Generic[S]): ...

def make() -> Sub: ...
def make_int() -> Sub[int]: ...
def make_recursive() -> Recursive: ...
