name: main

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          # - "3.14-dev" wait for beta 2

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: install dependencies
        run: pip install .[tests,asynq] pytest
      - name: test
        run: pytest pycroscope

  test-no-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: install
        run: pip install . pytest
      - name: test-no-deps
        run: pytest pycroscope
